#   Prueba de copiado de archivos
#
---
- name: Ejecutando un script
  hosts: 192.168.56.200
  vars:
    var_time: "{{lookup('pipe', 'date \"+%d%m%Y\"')}}"
  tasks:
  - name: Creando el directorio
    file:
      path: "/home/jesus/{{var_time}}"
      state: directory
      owner: "{{var_owner}}"
      group: "{{var_group}}"
      mode: "{{var_mode}}"
  - debug: var=var_time  
  - name: Copiando archivo 1
    copy:
      src: /home/jesus/{{nombreArchivo}}
      dest: /home/jesus/{{var_time}}/
      remote_src: yes
        
  - name: Copiando multiples archivos
    copy: src={{ rutaOrigen }} dest={{ rutaDestino }} remote_src=yes
    with_items:
      - { src: '{{file1}}', dest: '{{destino1}}' }
      - { src: '{{file2}}', dest: '{{destino2}}' }
     
    
    
    
#    with_together:
#      - [ '{{file1}}', '{{file2}}' ]
#      - [ '{{destino1}}', '{{destino2}}' ]

  #- name: Mostrar archivos de status
  #  command: cat "/home/jesus/job.status"