#   Prueba de copiado de archivos
#
---
- name: Ejecutando un script
  hosts: 192.168.56.200 
  tasks:
  - name: Creando el directorio
      ansible.builtin.file:
        path: /home/jesus/newdir
        state: directory
        mode: '0755'

  - name: Copiando archivo 1
    copy:
      src: /home/jesus/test.sh
      dest: /home/jesus/newdir/
    
  
  #- name: Mostrar archivos de status
  #  command: cat "/home/jesus/job.status"