#   Prueba de copiado de archivos
#
---
- name: Ejecutando un script
  hosts: 192.168.56.200
  vars:
    var_time: "Var:{{lookup('pipe', 'date \"+%H%M%S\"')}}"
  tasks:
  - name: Creando el directorio
    file:
      path: "/home/jesus/var=var_time}"
      state: directory
      owner: jesus
      group: jesus
      mode: '0755'

  - name: Copiando archivo 1
    copy:
      src: /home/jesus/test.sh
      dest: /home/jesus/{{fecha}}/
      remote_src: yes
    
  
  #- name: Mostrar archivos de status
  #  command: cat "/home/jesus/job.status"