#   Prueba de copiado de archivos
#
---
- name: Ejecutando un script
  hosts: 192.168.56.200
  vars:
    var_time: "{{lookup('pipe', 'date \"+%d%m%Y\"')}}"
  tasks:
  - name: Creando el directorio
    file:
      path: "/home/jesus/var=var_time}"
      state: directory
      owner: jesus
      group: jesus
      mode: '0755'
  - debug: var=var_time  
  - name: Copiando archivo 1
    copy:
      src: /home/jesus/test.sh
      dest: /home/jesus/mkdssss/
      remote_src: yes
    
  
  #- name: Mostrar archivos de status
  #  command: cat "/home/jesus/job.status"